UPDATE CS_ME_CDDEP SET FLAG_ENVOI = NULL WHERE MAGIC BETWEEN 432524 AND 438500;

UPDATE CS_ME_CDINV SET FLAG_ENVOI = NULL;
DELETE FROM LISTE_ERREUR WHERE SIMULATION_ID IN (SELECT "id" FROM SIMULATION WHERE FLUX_ID = 7);
DELETE FROM ECRITURE_COMPTABLE WHERE PIECE_ID IN (SELECT "id" FROM PIECE_COMPTABLE WHERE FLUX_ID IN (7));
DELETE FROM PIECE_COMPTABLE pc WHERE FLUX_ID IN (7);
DELETE FROM SIMULATION_CDDEP sc ; -- 6
DELETE FROM SIMULATION_CDINV sc ; -- 7
DELETE FROM SIMULATION WHERE FLUX_ID IN (7);
DELETE FROM OAS_LINKLINE WHERE LINKCODE = 'INVOICE';
DELETE FROM OAS_LINKHEAD WHERE LINKCODE = 'INVOICE';
SELECT * FROM OAS_LINKQTY WHERE QTYVALUE_DP <>0;
UPDATE OAS_LINKQTY SET QTYVALUE_DP = 0 WHERE QTYVALUE_DP = 2;
SELECT * FROM OAS_LINKHEAD WHERE LINKCODE = 'INVOICE';
UPDATE OAS_LINKHEAD SET POSTED = 46 WHERE LINKCODE = 'INVOICE';
COMMIT;


DELETE FROM SIMULATION_CDMOV; -- FLUX 5
DELETE FROM SIMULATION_CDCOH sc ;
DELETE FROM SIMULATION_CDPOH;

-- DELETE FROM  CS_ME_CDCOL  ;
-- DELETE FROM CS_ME_CDCOH;
-- DELETE FROM CHARGEMENT WHERE FLUX_ID = 3;

DELETE FROM OAS_LINKQTY Q 
 WHERE EXISTS (SELECT 'Y' 
                  FROM OAS_LINKLINE L 
                 WHERE L.LINKCODE = 'VEH_FIN' 
                   AND Q.CMPCODE  = L.CMPCODE  
                   AND Q.DOCCODE = L.DOCCODE
                   AND Q.DOCNUM = L.DOCNUM
                   AND Q.DOCLINENUM = L.DOCLINENUM); 
DELETE FROM OAS_LINKLINE WHERE LINKCODE = 'VEH_FIN';
DELETE FROM OAS_LINKHEAD WHERE LINKCODE = 'VEH_FIN';
 


UPDATE CS_ME_CDCOH SET FLAG_ENVOI = NULL;
COMMIT;
